# Development Dockerfile for {{ cookiecutter.project_slug }}
#
# This file is used for development commands, and 
# interactive shell's with your package.
FROM mhoush/py-dev:latest

ENV PROJECT {{ cookiecutter.project_slug }}
ENV PROJECT_PYTHON 3.5.0

RUN /bin/bash /entrypoint.sh install
